/*
-- Query: SELECT nomeCompleto AS Nome, IFNULL(email,'jbcred@jbcred.com.br') AS Email
FROM funcionarios
WHERE nomeCompleto IS NOT NULL 
	AND TRIM(nomeCompleto) <> ''
-- Date: 2022-08-04 15:57
*/
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ADRIANA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ELAINE FLORENTINO DE GOIS','ELAINE_FINANCEIRO@JBCREDSA.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('APARECIDA CLEMENTINO DE MORAES','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('FERNANDA VIEIRA SANTOS','JBCRED08@TERRA.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ELISA GOMES FRANCISCO NASCIMENTO','elisa.gomes.ctb@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('VANESSA DA SILVA','VANESSA_FINANCEIRO@JBCREDSA.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LUANA','LUANA_FINANCEIRO@JBCREDSA.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('NILZA','NILZA_FINANCEIRO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('QUITERIA DOS SANTOS MENDONÇA','COBRANCA@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CARLOS','CARLOS@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MARIA DA LUZ OLIVEIRA','MARIA@JBCREDSA.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JULIANA VIEIRA BARROS','JULIANA_CREDITO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('DANIELLE REGIS','DANIELLE_FINANCEIRO@JBCREDSA.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ROSELI CAVALCANTI DA SILVA MELLO','ROSELI@JBCREDSA.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MARIA VALDIZIA VIANA BANDEIRA','VAL_COMERCIAL@JBCREDSA.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('HELOIZA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LUCIDALVA PEREIRA CURSINO','LCURSINO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MAGALI MARÇAL','MAGALI_FINANCEIRO@JBCREDSA.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('FABIANA FERREIRA DOS SANTOS NASCIMENTO','FABIANA_CREDITO@JBCREDSA.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('SILVIA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ROSELI DE SOUZA CAPASSO','ROSE_FINANCEIRO@JBCREDSA.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CLEONICE LEANDRO CAVALCANTI DA SILVA','CLEO_FINANCEIRO@JBCREDSA.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ANDRESA MACEDO AMBROSIO','ANDRESA_CREDITO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('NATHALIA AZEVEDO MARQUES DIAS ','NATHALIA_CREDITO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ALEXANDRA','ALEXANDRA_COBRANCA@JBCREDSA.COM.BR ');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CLAUDIA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('VALQUIRIA BATISTA DA SILVA','VALQUIRIA_CREDITO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JENIFER CRISTINA KAIZER','JENIFER_FINANCEIRO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MILENA','MILENA_COBRANCA@JBCREDSA.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MELINA ISOLA TEIXEIRA MORAIS','MELINA_CREDITO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ALESSANDRA RODRIGUES DIAS','ALESSANDRA_COMERCIAL@JBCREDSA.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('THAIANE','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ROBERTA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MISLENE FELIX DA SILVA','MISLENE.FELIX@JBCREDSA.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('KEILA SILVA SANTOS BATISTA','KEILA@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('AMANDA CRISTINA DAVI','AMANDA_ATENDIMENTO@JBCREDSA.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('HOSANA RIBEIRO ANDRADE','hosana.ribeiro.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('EVELIN','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('THAYS','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CAMILA DE BARROS COUTINHO','CAMILA_CREDITO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ANA PAULA BRASIL SIQUEIRA BUENO','ANA_CREDITO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('WAGNER CAETANO PIMENTA DE MORAIS','WAGNER@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MARCIA RIBEIRO MARQUES','MARCIA_CREDITO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('SCARLLATTI','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JOICE','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ELENICE','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LUCILENE','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LUCIENE','LUCIENE_COBRANCA@JBCREDSA.COM.BR ');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('BETE','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ERIKA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JULIANE','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('KELCY','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ANA CLAUDIA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('TAIS SOUZA DA COSTA','tais.souza.crd@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CARINA DA SILVA PEDRERO PINTO','CARINA_CREDITO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JOANA EDITE BATISTA DA SILVA','JOANA_CREDITO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('STEFFANY','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('DEBORA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LETICIA','LETICIA_COBRANCA@JBCREDSA.COM.BR ');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MAYLA MONIQUE BASLER','MAYLA_COBRANCA@JBCREDSA.COM.BR ');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('SIMONE BALBINO LEAL','SIMONE.LEAL@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LUCIA NUNES DE SOUZA','lucia.nunes.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('SHEILA DA SILVA SALOMÃO','SHEILA_COBRANCA@JBCREDSA.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MARIA ISRAELY COSTA CANEDO DE ARRUDA','maria.israeli@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MAIRA SERDEIRA SANTOS','MAIRA_CREDITO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('SARA SANTIAGO CORREA DA SILVA','SARA@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('SHIRLEI','SHIRLEI@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('SIMONE SIRLEY ARRUDA BERNARDI','simone.arruda.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('HELENA DE ARAUJO SANTOS VALENTE','HELENA@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('RENATA SAMPAIO GASPAR','RENATA_JURIDICO@JBCREDSA.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JULIANA PATRICIO DE LIMA','juliana.lima@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('FABIO ROBERTO DA COSTA','FABIO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MARI SOUZA DE ANDRADE','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('TATIANE CRISTINE','TCRISTINE@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MARCO ANTONIO DA SILVA','MARCO.ANTONIO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('WIVELLIZE PONTES ANGELO','wivelize.pontes@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ROBERTA NASCIMENTO SANCHES','roberta.nascimento@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ELIZABETH JESUS','EGONCALVES@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CICERA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CAROLINE PANSUTTI ROMERO HAMAZUMI','carolinepansutti.jur@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('KELLY CRISTINA OLIVEIRA','KOLIVEIRA@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('SUELEN CORDEIRO SILVA SARAMELA','SUELEN.SARAMELA.CBC@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('REGIANE DOS SANTOS RONDÃO','regiane.rondao.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('GIRLENE DOS SANTOS SOUZA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JENNIFER FERREIRA DIOGO','JDIOGO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('EVELYN CRISTINA MORAES SOUZA RIBEIRO','evelyn.cristina.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JAQUELINE MARIA DE SOUSA GOMES VIANA','jaqueline.viana@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('FABIO HENRIQUE CESCHINI','FCESCHINI@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ANDREIA CASSIA APAREIDA TAMPELLI','ATAMPELLI@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('FRANCISCA VALERIA DA COSTA TEODORO','FTEODORO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ROBENNY COSTA PEDROSO DA MOTA','RMOTA@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JHENIS SOUZA TOZATTO','JLOZATTO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('THAINA GARCIA MENDES','thaina.mendes.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('THAMIRES LIMA','TLIMA@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('GABRIELA MARTINS DA CRUZ SILVEIRA','GMARTINS@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ALINE BEZERRA DIAS','aline.bezerra@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MARIA EUDENIS LIMA MATIAS','maria.matias.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('THIFANI SILVA ALVES BASILIO','talves@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('PAULO FERREIRA DO NASCIMENTO','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MELISSA DA SILVA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('KAREN CRISTINA ZANON CABRAL','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('THAMIRES GOMES SODRE','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ROSELY SALVADOR DE MOURA','rosely.salvador@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('FABIO LUIZ MOREIRA BEZERRA','fmoreira@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LETICIA CAROLINE TRINDADE SILVA','LTRINDADE@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LARISSA MOURA PORTUGAL ALMEIDA','LALMEIDA@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MICHELLE SOARES SILVA','MSOARES@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LUCAS DONATO','LDONATO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JULIANA DE MATOS EVANGELISTA','juliana.evangelista@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('AMANDA SOUZA IAQUINTO','AMANDA.SOUZA.AQV@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ARIEL DO NASCIMENTO','ariel.nascimento@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('VITORIA NICOLE MARTINS DOS SANTOS','');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JHENIS SOUZA LOZATTO','JLOZATTO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CAROLINE LIMA DA SILVA','CLIMA@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('NATHANE DOS SANTOS BORGES','NBORGES@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CASSIA NOVAES DOS SANTOS','CSANTOS@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MILENA DOS SANTOS RUFINO','MRUFINO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('KLEBER ALVES TEIXEIRA','KTEIXEIRA@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ALINE VITOR SOARES','ASOARES@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('GABRIELA BORGES DE SANTANA','GSANTANA@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('NATALIA LOPES DOS SANTOS','NSANTOS@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ANDRESSA MATIAS CONCEIÇÃO','ACONCEICAO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ALESSANDRA FERREIRA DA SILVA','AFERREIRA@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('GILDETE PEREIRA DE JESUS DAMASCENA','GGAMA@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LORRANE BRANDINO','lorrane.brandino@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('EVELYN DE MELO E SILVA','ESILVA@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('PRISCILA EVELYN DA SILVA','PSILVA@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CAROLINE SAOUD BOUSQUETE ','caroline.saoud@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('GIDALVA DOS SANTOS SILVA','gidalva.silva@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('BRUNA LILIANE ARAUJO DOS SANTOS','BSANTOS@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('GIOVANA ZUCATO','GZUCATO@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ANDRESSA RAIA','ARAIA@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('BIANCA GONÇALVES FERNANDES','bianca.fernandes.arq@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('THAINA APARECIDA BARBOSA MARIANO GUIRRA','thaina.guirra.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('NATHALIA CRUZ MENDONÇA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('VIVIANE PINHEIRO','viviane.moura.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JENNIFER MELO DORNELLES','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('YANCA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ALICE DILMARI DE SOUZA BENTO','alice.souza.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('GABRIELA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('PAULO HENRIQUE CORRETOR','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('RODRIGO DELLA CASA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('NATALY','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ELISANDRA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('EDUARDO','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CARLOS ALEXANDRE TANIKAWA','TANIKAWA@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('AUDITORIA INTERNA','auditoriainterna@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('OUVIDORIA','OUVIDORIA@JBCREDSA.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('BACEN','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ADNA VIRGINIO DINIZ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JEISILANE TEIXEIRA CARVALHO','jeisilane.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('TAINA APARECIDA SAMBEL DOS SANTOS','taina.santos.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('TAYNARA BARBOSA BEZERRA DA SILVA','taynara.silva.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ALINE BELARMINO BERGAMO','aline.bergamo@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('NATALIA DOS ANJOS OLIVEIRA','nathalia.oliveira@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('KAROLINE SUSIN PAULINO','karoline.paulino@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('BARBARA ESTER VICENTE SILVA DOS SANTOS DIAS','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('BRUNA MARIANA RATTIS PEREIRA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('DAMIANA RAQUEL VIEIRA MENDES','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('KAREN PIRES DE OLIVEIRA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LUANA LETICIA SILVA CONCEICAO','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('SABRINA VERONICA GODOI GOMES','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('SHEILA CARVALHO','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('STEFANI BARROS ALVES','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('RAUL CORDEIRO MIRANDA','raul.miranda@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ALINE ALMEIDA SANTOS','aline.almeida.dig@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ELEN MOREIRA RODRIGUES DE SOUZA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ELEN MOREIRA RODRIGUES DE SOUZA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('STEFANY RIBEIRO','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('GISLAINE APARECIDA MARTINS DA SILVA','gislaine.martins.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JESSICA DA SILVA ALVES','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('SAC - JBCRED','JBCRED@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('DAIANE CRISTINA LEONEL','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('TIFANY VIEIRA DE SOUZA','tifany.souza.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CAROLINE ROCHA FERREIRA','caroline.rocha.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LAYLA BEATRIZ SIQUIEIRA REZENDE','layla.rezende.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LUCIANA LOPES FERREIRA DE SA','luciana.lopes.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('GABRIELLA DA SILVA GOMES','GABRIELLA.GOMES.CBC@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LUANE MATIAS DA SILVA','LUANE.MATIAS.JUR@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('GABRIELA ALVES DE LIMA','gabriela.alves.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MICHELLE SOARES SILVA','michele.soares.rcp@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('GISELE ALBERTI PEREIRA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('EMERSON STELLA','EMERSON_AUDITORIA@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LARISSA KIMBERLY GLORIA BATISTA DE ARAUJO','larissa.kimberly@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ALINE OLIVEIRA DA SILVA','aline.silva.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('INGRIDY CAROLINE DA SILVA','ingridy.silva.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('BIANCA BERNARDO DE ALMEIDA','bianca.andrade.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CIBELY MARA GEREMIAS SALES','CIBELY.SALES.CBC@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('THAINA WINNE ARAUJO','thaina.winne.rcp@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LUANA RODRIGUES GALVANI','LUANA.GALVANI.RCP@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ERICA SOUZA CRUZ','erica.cruz.jur@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JAQUELINE APARECIDA VELOSO','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('PROCESSO','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ANDERSON DA SILVA ALBUQUERQUE','AALBUQUERQUE@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('RUTH GOMES MOREIRA','ruth.gomes.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CAMILA NASCIMENTO DE OLIVEIRA','CAMILA.OLIVEIRA.CBC@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('BRUNNA HONORATO NASCIMENTO DA SILVA','brunna.honorato.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LAURA OLIVEIRA DA SILVA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('KATHLYN ALEIXO LIMA','kathlyn.aleixo.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('DAIANE ROJO NUNES ALVES','daiane_comercial@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JAIRO WESLEY MARTINS DOMINGUES','jdomingues@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MAURICIO MOURA DE MELO JUNIOR','mjunior@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MARIANA DO NASCIMENTO OLIVEIRA','mariana.nasc.arq@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('NATHALIA OLIVEIRA DE ALMEIDA','NATHALIA.ALMEIDA.CRD@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('FULANA DE TAL SILVA','Fulana.Silva.cdr@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LAYS CUNHA TOMAZETI','LAYS.CUNHA.CBC@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('DANIELLE BOTARO DA SILVA','DANIELLE.SILVA.CBC@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MYRYAN CHRISTIANE SILVA NUNES NOVAIS','MYRYAN.NOVAIS.JUR@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CAMILA DE CARVALHO AGUIAR','CAMILA.CARVALHO.CBC@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('GIOVANNA GRACIA MELLO','GIOVANNA.GRACIA.CBC@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('FERNANDA RAMOS DE SOUZA','FERNANDA.SOUZA.CRD@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('WALKIRIA REBECA PINTO','WALKIRIA.REBECA.CRD@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('INGRID RAMALHO','INGRID.RAMALHO.CBC@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CAROLINE NOCETE DIAS HERCULANO','CAROLINE.DIAS.CBC@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LILIAN ALVES DE BRITO MORAES','lilian.moraes.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ALEXANDRE TURON CAMPOS','acampos@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('DAYANE POSTIGO LADISLAU','dayane.ladislau.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('THAIS DA SILVA FERREIRA','thais.ferreira.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ALINE DA CONCEICAO RODRIGUES','aline.rodrigues.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LAIS DOS SANTOS CORDEIRO','lais.cordeiro.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('BEATRIZ MARIA DA SILVA','beatriz.silva.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JANAINA DE ARAUJO CANDIDO','janaina.candido.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LINDYELMA ALVES DA COSTA FRANCA','lindyelma.franca.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LAISLA LUCIANO DE ARAUJO','laisla.araujo.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JESSICA MILENA SANTANA','jessica.miline.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('NATHALIA FRANÇA OLIVEIRA','nathalia.franca.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('TALITA SANTOS TENORIO','talita.tenorio.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('THAIS SILVA SANTOS','thais.ssantos.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('NAYARA DOS REIS LEITE SANTANA','nayara.leite.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MARIANA AMORIM COSTA','mariana.costa.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('KEVELIN DOS SANTOS FERREIRA','kevelin.ferreira.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('NATALIA FACOTI DA SILVA','natalia.facoti.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('PALOMA SOARES FAGUNDES','paloma.fagundes.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('TACHIE MARTINS ALMEIDA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('KAREN OLIVEIRA CARVALHO','karen.carvalho.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CRISTIANE GAMBOA FLORENCIO DA SILVA','cristiane.gamboa.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ANA PAULA RAMOS DOS SANTOS','ana.santos.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MART CRUZ DE MOURA','mart.cruz.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('WILIAN MARTINS','wilian_martinns@hotmail.com');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LIANA DELLA CASA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MARCELO ALCIDES IGNACIO PEREIRA','marcelo.pereira.cdb@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('IASMIN MIRELLY DA SILVA','iasmin.silva.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MARILIA PURIFICACAO','marilia.purificacao@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ANGELICA KAZLAUSKAS','angelica.kazlauskas.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('KATE REGINA PRESTES SAMPAIO','kate.sampaio.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('TATIANE OLIVEIRA DOS SANTOS','tatiane.oliveira.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('Danielle Soares Alves','danielle.alves.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('GREYCE ELLEN DE OLIVEIRA','greyce.oliveira.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('YOHANA FERREIRA GOMES','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MAYARA MENDONCA PROFETA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('DEBORAH ALINE LIMA DE OLIVEIRA','deborah.oliveira.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('EDUARDO FIGUEIREDO SENA MOREIRA','esena@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('YARA TEIXEIRA LIMA','yara.lima.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('NATHIELI SANTOS ARAUJO','nathieli.araujo.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CARLOS ALBERTO SOUZA PINCER','cpincer@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LEILIANE GOMES DE SOUSA','leiliane.sousa.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MAYARA DE PADUA DOS SANTOS','mayara.padua.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('DANIELA CORDEIRO GARCIA SANTOS','daniela.santos.cdc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JESSICA CRISTINA DE OLIVEIRA','jessica.oliveira.cdc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MARIANA BRITO PEREIRA','mariana.brito.cdc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LETICIA TAMIRES DAL SANTO ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('VINICIUS REIS','vreis@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('AMANDA GONCALVES DA SILVA			','amanda.goncalves.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ALINE MELO PEQUENO','aline.pequeno.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('TESTE CREDITO','teste-credito@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('SIMONE BERNARDES MIGUEL','simone.miguel.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LAIS FRANCA DA SILVA','lais.franca.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('FERNANDA COSTA CANDINI MOTA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('RAFAELA DOS SANTOS FERREIRA','rafaela.ferreira.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('BEATRIZ KIOHARA DE ARAUJO','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ADRIANE SILVA MENDES','adriane.mendes.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('NAYARA AIELLO DE FARIAS','nayara.farias.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('NAYARA AIELLO','NAYARA.FARIAS.CBC@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ADILSON WOHNRATH','adilson.wohnrath.pds@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MARIBEL APAZA RIOS','maribel.rios.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LETICIA ADRIANA OLIVEIRA DE LIMA','leticia.lima.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('GABRIELA LIMA ALCANTARA','gabriela.lima.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CELINY LOPES OLIVEIRA','celiny.lopes.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('SHIRLEI CRISTINA DE MENDONCA V PEREIRA','shirlei.pereira.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('RAINY MORAIS DA SILVA RODRIGUES','rainy.rodrigues.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('THALIA KEYLER GOMES DE OLIVEIRA','thalia.gomes.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ALESSANDRA LEITE DA SILVA','alessandra.silva.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MARCELA LIMA DA MACENA','marcela.macena.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('BRUNO CESAR PASQUINI','bruno.pasquini.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CESAR KAZUSHI YAMANISHI','cesar_y@uol.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ALEX CAMPOS','alex.campos.com@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('GABRIEL BONAVIGO DACAL','gabriel.dacal@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('BRUNA TARSILA GOMES ','bruna.gomes.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('KATHERINE LAILA RODRIGUES FERREIRA','katherine.rodrigues.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CRISLENE COSTA DOS SANTOS','crislene.santos.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CAIO BIANCALANA','cbiancalana@penso.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('KAMILI SOARES DOS SANTOS','kamili.santos.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MILENE NUNES DOS SANTOS','milene.nunes.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CAROLINE DE CAMARGO','caroline.camargo@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MATHEUS FELIX DA SILVA','mfelix@penso.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('PRISCYLA AMARAL LOPES RECCO','priscyla.recco@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('THAIRINE BARBOSA DE SANTANA','thairine.santana.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ALEX BELLINTANI ROSA','alex.rosa.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ANDRESSA GUILMO NOVO ALBUQUERQUE DOS SANTOS','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JACIELE FELIX DE FONTES','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ARIADNE DE CASTRO TEIXEIRA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CAROLINA CORREA','carolina.correa.com@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LUCILENE EUGENIA GUIMARAES FERREIRA','lucilene.ferreira.cob@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('VALDIRENE APARECIDA ANDRADE GONZALES','valdirene-gonzales.cob@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MICHELE SOARES MACEDO ZAGO','michele.zago.cob@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('VIVIANE PINHEIRO MOURA','vivane.moura@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('TAMARA MARTINS','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LEIA SOARES DE LIMA','leia.lima.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ALANIS CARVALHO TOBIAS','alanis.tobias.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('TAYARA MARTINS CHULTS','tayara.chults.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MIGUEL COUY','mcouy@penso.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('SILVANA DE OLIVEIRA DA SOLVA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MAYARA CEARA SILVEIRA VIANA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('FERNANDA BRUNET CORREA DE BRITO','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ANDRESSA DE OLIVEIRA DOS SANTOS','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ANDREIA DOS SANTOS','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CAMILA CRISTINA CAMARGO','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('GIOVANNA GONÇALVES SANTOS','giovanna.santos.cbc@jbced.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ANDRE GODOY ','agodoy@penso.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('PRISCILA LIMA RODRIGUES CARMO','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('NATALIA SPOSITO DA SILVA SANTOS','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ANA LUCIA DE ANDRADE BEZERRA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CAMILA ANDRADE SILVA RODRIGUES','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('VANESSA APARECIDA NUNES NOGUEIRA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('SANDRA FERNANDES SILVA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('RENATO VARGAS CORREIA DA SILVA','renato.vargas.cmp@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('BEATRIZ RODRIGUES FORTE','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ANA LUIZA FERRREIRA DOMINGUES','ana.domingues.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MAYARA DE SALES COSTI','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('DAYANE MENDES DA SILVA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LUCIANA YUMIKO NAMIOKA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('DENISE CAROLINA DE FARIA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('NICOLY CARVALHO ARAUJO','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('RAFAELA MARTINS DA SILVA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('PAULICEIA DE SOUSA PINTO','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('THAIS CAMILA DA SILVA','thais.moreira.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('PAMELA PEREIRA REHEM','pamela.rehem.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('SILVANA VIANA DA SILVA','silvana.viana.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LETICIA IESCA RODRIGUES','leticia.rodrigues.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('GRACIELE SALES MEDEIROS','graciele.sales.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LUCIMONIK MELO DA SILVA','lucimonik.melo.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LEONARDO PAULO MACEDO','lpmacedo@penso.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LAIS JESUS MELO DE CARVALHO','lais.carvalho.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('VITOR AUGUSTO OLIVEIRA SANTOS','VSANTOS@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ADRIELE NAYARA MARAMALDO','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('AMANDA PIMENTEL LIMA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('BEATRIZ CRISTINA LIMA DA SILVA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CAROLINA CAMARGO CLEMES','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('DAIANE MIRA DA SILVA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('DANIELA CRISTINA DO NASCIMENTO LOPES','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('NAYARA ALVES VIEIRA SOUSA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ANA LUCIA PEREIRA LOPES ALVES DE SOUZA ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('DAIANE ALVES NASCIMENTO','daiane.nascimento.crd@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ALEXANDRA OLIVEIRA BARBOSA ','ALEXANDRA.OLIV.CRD@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MARIA APARECIDA SANTOS DA SILVA ','');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('WILLIAN SANTOS','M16@M16.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('NARRIMAN REIS FAGUNDES ','NARRIMAN.REIS.CBC@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ANDRESSA ALVES SANTOS ','ANDRESSA.SANTOS.CBC@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('TAMIRES FRANCIS MEDEIROS ','TAMIRES.MEDEIROS.CBC@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LARISSA NONATO MARCO ','larissa.nonato.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ANA CAROLINA ALVES SANTOS FUCUTA','ANA.FUCUTA.CRD@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('HELEN SANTOS MACHADO','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LILIAN PAMELA DA SILVA LIMA','LILIAN.LIMA.CRD@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('DANIELA ZAMARO CAMPOS ','DANIELA.CAMPOS.CBC@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('STEPHANIE XAVIER','STEPHANIE.XAVIER.CBC@JBCRED.COM');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LARISSA SABIONI AUGUSTO','LARISSA.SABIONI.CRD@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('THAIS ESTERQUELE DE HOLANDA ','THAIS.HOLANDA.CBC@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MARIA ROSENI DE SOUSA ','MARIA.SOUSA.CBC@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('DAYANA SANTOS FARIAS ','DAYANA.FARIAS.CRD@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LUANA ASSUMPCAO FERMIANO ','LUANA.FERMIANO.CBC@JBCRED.COMBR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('DALVENISA LENITA GOMES ','DALVENISA.GOMES.CBC@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LUANA ASSUMPCAO','LUANA.FERMIANO.CBC@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CAMILLY MARTINS OLIVEIRA ','CAMILLY.OLIVEIRA@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('NAIANA CALIXTO DOS SANTOS ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('KIMBERLY DO ROSARIO ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JESSICA SABRINA DA SILVA DE CASTRO ','JESSICA.CASTRO.CRD@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('KAREN ARAUJO LOPO ','KAREN.LOPO.CRD@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LUANA SANTOS DE LIMA ALMEIDA','LUANA.LIMA.CRD@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MAYBE GIOVANNA CONCEICAO CASSIMIRO','MAYBE.CASSIMIRO.CRD@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CAMILA CONCEICAO DE ASSIS DA SILVA ','CAMILA.ASSIS.CRD@JBCRED.COM.BR');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ADRIELE BATISTA SANTOS ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ADRIELE SANTOS ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ADRIELE B. SANTOS','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LORENA CARVALHO SILVA ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LARISSA MOURA FONSECA ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('AMANDA APARECIDA CLEMENTE SILVA PEREIRA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('AMANDA APARECIDA CLEMENTE ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('TICIANE MANGUEIRA RODRIGUES ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('VITÓRIA MATHIAS PEREIRA ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LORENA CARVALHO ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('AMANDA RAFAELA MOTA SOARES ','atendimento.direto35@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JULIA RODRIGUES DO VALLE ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('GISELE SIMONCINI ARAÚJO','atendimento.direto36@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CAMILA MACIEL GERONIMO','atendimento.direto37@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CICERA JOSEFA DO NASCIMENTO','cicera.nasc.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('REGIANE DOS SANTOS SILVA','regiane.silva.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ALANNA KIMBERLY MACIEL ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('BRUNNA VICTORIA SANTOS RIBEIRO ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ANA BEATRIZ NUNES GOMES ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JULIANA BRAZ DE SOUSA REIS ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('TAUANA PEREIRA DE OLIVEIRA ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('HILLARY FAYOLA SILVA DOS SANTOS ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CAROLINE PETRUCELLI','carol.petrucelli.cbc@jbcred.com.br ');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('KAROLINE FERREIRA DOS SANTOS ','karoline.santos.cbc@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('KAROLINE FERREIRA ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('LETICIA ANDREZA TIBURCIO','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JULIANA APARECIDA BONGESTOB ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('JULIANA AP BONGESTOB','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('GIOVANNA MILENA DE LIMA SILVA ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MARIA JANAINA GOMES DE OLIVEIRA ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MARIA JANAINA GOMES ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('WILLIAN OLIVEIRA DOS SANTOS ','m16@m16.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('SUELLEN DE CARVALHO RAPHAEL','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('BARBARA NICOLI DUARTE LASS ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('MIKELLE DEYSIANE FERREIRA SOARES ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('RUTE ARAUJO DA FONSECA ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('KEYLLA RUAMA FERREIRA LIMA ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('CAROLINA CONCEICAO DOS SANTOS ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('RENATA DE ANDRADE SILVA ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ANANDA PIRES DA SILVA ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('AMANDA JEANE COSTA ','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('SUPERVISOR','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('ROSANA GONÇALVES SILVA DE SOUZA','jbcred@jbcred.com.br');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('FABIO RODRIGUES DE ALMEIDA','fabio-rodrigues-almeida@hotmail.com');
INSERT INTO `User` (`Nome`,`Email`) VALUES ('GIRLENE DOS SANTOS SOUZA','jbcred@jbcred.com.br');
